commands:
  rtp:
    cooldown-seconds: 30
    max-tries: 10
    radius:
      min: 2000
      max: 10000
    unsafe-blocks-regex:
      - LAVA
      - WATER
      - .*_LEAVES
      - (TALL_)?SEAGRASS
  tpa:
    request-lifetime-seconds: 60

tab:
  enabled: true
  update-ticks:
    header: -1
    footer: 20
    player-names: 400

auto-messages:
  enabled: true
  interval-seconds: 120