commands:
  rtp:
    enabled: true
    delay-seconds: 30
    max-tries: 10
    radius:
      min: 2000
      max: 20000
    unsafe-blocks-regex:
      - LAVA
      - WATER
      - .*_LEAVES
      - (TALL_)?SEAGRASS